name: GitHub Vars

on:
  workflow_dispatch

env:
  MY_VAR: workflow

jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      MY_VAR: jobs
    steps:
      - name: Print
        env:
          MY_VAR: steps
        run: |
          echo 'Workflow Level: ${{ vars.MY_VAR }}'
          echo 'Job Level: ${{ env.MY_VAR }}'
        
